// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunicipalTax.DAL;

namespace MunicipalTax.DAL.Migrations
{
    [DbContext(typeof(MunicipalTaxContext))]
    [Migration("20200820162106_InitialDbSchema")]
    partial class InitialDbSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("MunicipalTax.Entity.MunicipalityTax", b =>
                {
                    b.Property<int>("MunicipalityTaxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MunicipalityName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("Tax")
                        .HasColumnType("REAL");

                    b.Property<int>("TaxType")
                        .HasColumnType("INTEGER");

                    b.HasKey("MunicipalityTaxId");

                    b.ToTable("MunicipalityTaxes");
                });
#pragma warning restore 612, 618
        }
    }
}
